include:
  - project: $PROJECT_TEMPLATES_GITLABCI_PATH
    ref: 1.1.1
    file: '.gitlab-ci-java-basic.yml'

variables:
  DOCKER_IMAGE: $DOCKER_URL/maven:3.9.6-eclipse-temurin-21
  # Pour l'instant (mars 2024, SonarQube 9.9.3, PMD 6.45.0), plantee "Unsupported Java version for PMD: 21",
  # il faut donc faire l'analyse Sonar en Java 17 (utilisation d'un profil Maven)
  # DOCKER_IMAGE_SONARQUBE: $DOCKER_URL/maven:3.9.6-eclipse-temurin-17
  DOCKER_IMAGE_SONARQUBE: $DOCKER_URL/maven:3.8-openjdk-17
  SONAR_MAVEN_GOAL: org.sonarsource.scanner.maven:sonar-maven-plugin:$SONAR_MAVEN_PLUGIN_VERSION:sonar -Psonar
  # Pour l'instant (mars 2024), trace "Could not parse class file FastDoubleSwar.class,
  # java.lang.UnsupportedOperationException: Hashing for Java 21 and beyond is not supported yet".
  # Elle n'empeche pas que l'analyse se deroule correctement.
  # Pour supprimer cette trace, il semble qu'il faille attendre que le clm-maven-plugin (actuellement
  # en 2.47.10-01) soit capable d'analyser du Java 21.
  # Les valeurs ci-dessous actuellement menent a la meme trace :
#  DOCKER_IMAGE_NEXUS_IQ: $DOCKER_URL/maven:3.8-openjdk-17
#  NEXUS_IQ_MAVEN_GOAL: com.sonatype.clm:clm-maven-plugin:$NEXUS_IQ_MAVEN_PLUGIN_VERSION:evaluate -Psonar

default:
  tags:
    - 'net:gold-dev'
