# Configuration file for the application. Used:
# - in "mvn spring-boot:run" mode
# - in Tomcat mode, with some values overridden by GoCD
# Necessary, otherwise "PKIX path building failed" error occurs when connecting to HTTPS FormServices
app:
  business:
    latest-component: 10
  nexusservices:
    connection-timeout-milliseconds: 5000
    minimum-size-file: 40000
    response-timeout-milliseconds: 30000
    ssl:
      enabled: true
    url: URL_NEXUS_REST
  security:
    token: TOKEN_BASE64

javax:
  net:
    ssl:
      trustStore: classpath:security/gina_20211015.jks
      trustStorePassword: 2vH-mc4j

logging:
  level:
    root: INFO
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

spring:
  main:
    banner-mode: log
