# Copy this file into file "application.yml", see the README file.
app:
  security:
    # A FAIRE : déplacer dans nexusservice
    token: TO_BE_PROVIDED (IN BASE 64)

  # A FAIRE : renommer "nexusservices" en "nexus"
  nexusservices:
    url: TO_BE_PROVIDED
    connection-timeout-milliseconds: 5000
    response-timeout-milliseconds: 30000
    minimum-size-file: 40000
    ssl:
      enabled: true

javax:
  net:
    ssl:
      trustStore: classpath:security/truststore.jks
      trustStorePassword: TO_BE_PROVIDED

logging:
  level:
    root: INFO
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

spring:
  main:
    banner-mode: log
