app:
  business:
    component:
      latest: 10
      minimum-size-file: 40000
  nexus:
    connection-timeout-milliseconds: 5000
    response-timeout-milliseconds: 30000
    ssl:
      enabled: true
    url: MISSING
  security:
    token-base64: MISSING

# not used if app.nexus.ssl.enabled = false
javax:
  net:
    ssl:
      trustStore: classpath:security/truststore.jks
      trustStorePassword: MISSING

logging:
  level:
    root: INFO
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

spring:
  main:
    banner-mode: log
    web-application-type: none
